# This is a generated file. Not intended for manual editing.
services:
  ordersmicroservice.api:
    build:
      context: "/home/farouk/RiderProjects/eCommerceSolution.OrdersMicroservice"
      dockerfile: "OrdersMicroservice.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57403"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ordersmicroservice.api:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57403"
    volumes:
    - "/home/farouk/RiderProjects/eCommerceSolution.OrdersMicroservice/OrdersMicroservice.API:/app:rw"
    - "/home/farouk/RiderProjects/eCommerceSolution.OrdersMicroservice:/src:rw"
    - "/home/farouk/.nuget/packages:/home/app/.nuget/packages"
    - "/home/farouk/.local/share/JetBrains/RiderRemoteDebugger/2025.2.3/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/642/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/farouk/.cache/JetBrains/Rider2025.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_10_27_07_16_35:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
